version: '3.4'

services:
  app-template-job:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile.job
    environment:
      TASK: "scrape"
      DATA_NAME: "elysee"
    command: ["python", "-m", "main"]