version: '3.4'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TASK: "scrape"
      DATA_NAME: "elysee"
    command: ["python", "-m", "main"]