FROM python:3.10-slim

WORKDIR /tmp
COPY requirements/requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

COPY src/api /opt/api
WORKDIR /opt/api

EXPOSE 80
CMD ["uvicorn", "api.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]
