name: Continuous Integration

on: [ push ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installing requirements
        run: |
          pip install --no-cache-dir --upgrade -r requirements/requirements.app.txt
          pip install --no-cache-dir --upgrade -r requirements/requirements.api.txt
          pip install --no-cache-dir --upgrade -r requirements/requirements.job.txt
          pip install --no-cache-dir --upgrade -r requirements/requirements.ci.txt

      - name: Run CI
        run: |
          PYTHONPATH=./src/job python -m mypy src/job
          PYTHONPATH=./src/job python -m flake8 src/job
          PYTHONPATH=./src/job python -m pytest src/tests
